name: kadal_aayus
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase Suite
  firebase_core: ^2.31.0
  cloud_firestore: ^4.17.1
  firebase_auth: ^4.17.1
  firebase_storage: ^11.7.7
  firebase_messaging: ^14.7.2

  # Core Feature Packages
  url_launcher: ^6.3.0
  location: ^6.0.2
  mapbox_maps_flutter: ^1.0.0 # Add this for the map view

  # UI
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
