// lib/models/alert.dart
import 'package:hive/hive.dart';

part 'alert.g.dart'; // This file will be generated by build_runner

@HiveType(typeId: 2) // Using a new, unique typeId
class Alert extends HiveObject {
  @HiveField(0)
  final String title;

  @HiveField(1)
  final String body;

  @HiveField(2)
  final String severity;

  @HiveField(3)
  final DateTime timestamp;

  Alert({
    required this.title,
    required this.body,
    required this.severity,
    required this.timestamp,
  });
}
