import 'package:hive/hive.dart';

part 'marine_weather_alert.g.dart'; // This file will be generated by build_runner

@HiveType(typeId: 1) // Using a unique typeId
class MarineWeatherAlert extends HiveObject {
  // --- THIS IS THE FIX ---
  // The field is now a 'double' named 'waveHeight', not a 'String' named 'message'.
  @HiveField(0)
  final double waveHeight;

  @HiveField(1)
  final DateTime alertTime;

  @HiveField(2)
  final String severity;

  MarineWeatherAlert({
    required this.waveHeight,
    required this.alertTime,
    required this.severity,
  });
}
